name: dotnetcore # workflow name

on: [push] # event trigger，什么事件触发 build

jobs:
  build:

    runs-on: ubuntu-latest # 指定 runner，使用 Github 提供的 runner

    steps:
    - uses: actions/checkout@v1 # checkout
    - name: Setup .NET Core # 设置 dotnet core 环境
      uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: 3.1.100
    - name: dotnet info # 输出 dotnet -info，查看 dotnet 版本信息
      run: dotnet --info
    - name: Build with dotnet
      run: |
        ls
        cd src
        ls
        echo ${{secrets.NUGET_AUTH_TOKEN}}
        if [ "1233211234567" = ${{secrets.NUGET_AUTH_TOKEN}} ]; then

          echo 'ok'

        fi
        echo 'no'
        pwd
        dotnet build Brook.Signalr.sln --configuration Release
